name: GitHub CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:
    types: [checks_requested]
  workflow_dispatch:
permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
        with:
          version: "10.8.0"
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: "package.json"
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
# test:
#   runs-on: ubuntu-latest
#   steps:
#     - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683# v4
#     - uses: pnpm/action-setup@v4
#       with:
#         version: "10.8.0"
#     - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e# v4
#       with:
#         node-version-file: "package.json"
#         cache: "pnpm"
#     - run: pnpm install --frozen-lockfile
#     - run: pnpm playwright install chromium
#     - run: pnpm test
#       env:
#         CI: true
